package main

import (
	"fmt"
)

func cmdTT() {
	fmt.Println("--------------cmdTT()-------------")
	fmt.Println("testing 包提供了三种测试方式: 单元(功能)测试、性能(压力)测试、覆盖率测试")
	fmt.Println(tab, "测试用例文件不会参与正常源码的编译, 不会被包含到可执行文件中")
	fmt.Println(tab, "测试用例的文件名必须以 _test.go 结尾")
	fmt.Println(tab, "测试函数的名称要以 Test 或 Benchmark 开头, 后面可以跟任意字母组成的字符串, 采用驼峰写法, 一个测试用例文件中可以包含多个测试函数")
	fmt.Println(tab, "单元测试以 (t *testing.T) 作为参数, 性能测试以 (t *testing.B) 作为参数")
	fmt.Println(tab, "测试用例文件使用 go test 命令来执行, 源码中不需要 main 函数作为入口, 所有以 _test.go 结尾的源码文件内以 Test 开头的函数都会自动执行")
	fmt.Println(tab, "测试公共API")
	fmt.Println(tab, tab, "包名遵循 packageName_test 规则")
	fmt.Println(tab, tab, "只能使用被测试的包导出的函数、方法、类型和变量")
	fmt.Println("----------------------------------")
	fmt.Println("go test 用于以代码包为单位对Go语言编写的程序进行测试")
	fmt.Println(tab, "-args	将命令行的其余部分(-args之后的所有内容)传递给测试二进制文件")
	fmt.Println(tab, "-c	编译二进制文件为 pkg.test 但不运行它们")
	fmt.Println(tab, "-exec prog	使用 xprog 运行测试二进制文件")
	fmt.Println(tab, "-i	安装测试文件的依赖项, 但不运行它们, 该选项已废弃, 编译的包自动缓存")
	fmt.Println(tab, "-o file	编译二进制文件并重命名")

	fmt.Println(tab, "-bench regexp 运行指定的基准测试任务, 所有的任务 -bench . 或者 -bench=.")
	fmt.Println(tab, "-benchtime t 指定每个基准测试任务的执行时间, t 类型为 time.Duration, 默认 1s")
	fmt.Println(tab, "-count n 指定每个测试任务执行的次数, 如果设置 -cpu, 则表示在每个 GOMAXPROCS 上执行的次数, 默认为 1,")
	fmt.Println(tab, " 如果指定 -fuzz, -count 不会被应用")
	fmt.Println(tab, "-cover 输出测试覆盖统计信息")
	fmt.Println(tab, "-covermode set,count,automic 设置覆盖统计的模式, 默认 set")
	fmt.Println(tab, "-coverpkg pattern1,pattern2,... 设置覆盖统计指定的包")
	fmt.Println(tab, "-cpu 1,2,4 指定测试任务使用的 GOMAXPROCS")
	fmt.Println(tab, "-failfast 当第一个测试任务失败后不再执行新的测试任务")
	fmt.Println(tab, "-fuzz regexp 运行指定的模糊测试任务")
	fmt.Println(tab, "-fuzztime t 指定每个模糊测试任务的执行时间, t 类型为 time.Duration, 默认为 forever")
	fmt.Println(tab, "-fuzzminimizetime t 指定每个模糊测试任务的最小执行时间, t 类型为 time.Duration, 默认为 60s")
	fmt.Println(tab, "-json	将测试输出转换为适合自动处理的JSON")
	fmt.Println(tab, "-list regexp 列出所有测试任务")
	fmt.Println(tab, "-parallel n 运行并行执行的任务的数量, 默认为 GOMAXPROCS")
	fmt.Println(tab, "-run regexp 运行指定的测试任务")
	fmt.Println(tab, "-short 告诉长时间运行的测试任务缩短它们的运行时间, 默认关闭")
	fmt.Println(tab, "-shuffle off,on,N 设置测试任务的执行顺序随机执行, 默认 off,")
	fmt.Println(tab, "-skip regexp 跳过指定的测试")
	fmt.Println(tab, " on 表示开启并使用系统时钟作为随机数种子, N 表示可传入 int64 的整数作为随机数种子")
	fmt.Println(tab, "-timeout d 设置任务执行的超时时间, 如果为 0 表示禁用超时, 默认 10m")
	fmt.Println(tab, "-v 输出详细信息")
	fmt.Println(tab, "-vet list 指定在 go test 命令执行期间使用 go vet 检查的逗号分隔的列表")
	fmt.Println(tab, "-trace trace.out 将运行时的日志写入指定文件, 使用 go tool trace 可以在浏览器内打开日志文件")
	fmt.Println("----------------------------------")

	fmt.Println("go tool 运行其他 go 命令")
	fmt.Println(tab, "-n	打印将要执行但不执行的命令")
	fmt.Println(tab, "")
}
