package main

import (
	"fmt"
	_ "reflect"
)

func init() {
	fmt.Println("func init() exec....")
}
func readme() {
	fmt.Println("---------------readme()---------------")
	fmt.Println("reflect: 主要用途使给定的程序动态地适应不同的运行情况. 利用面向对象建模中的多态性也可以简化编写分别适用于多种不同情形的功能代码")
	fmt.Println(tab, "Go语言提供了一种机制在运行时更新和检查变量的值, 调用变量的方法和变量支持的内在操作, 但是在编译时并不知道这些变量的具体类型, 这种机制被称为反射")
	fmt.Println(tab, "反射技术允许将对需要调用的对象的信息检查工作从编译期间推迟到运行期间再现场执行. 这样一来,可以在编译期间先不明确目标对象的接口名称、字段(fields, 即对象的成员变量)、可用方法,")
	fmt.Println(tab, "然后在运行根据目标对象自身的信息决定如何处理. 它还允许根据判断结果进行实例化新对象和相关方法的调用")
	fmt.Println("---------------")

	fmt.Println("reflect.Type 是对 key 的封装, 对 key 的操作, 通常使用 reflect.TypeOf() 获取")
	fmt.Println(tab, "Type 表示变量声明时的类型 例如 int, main.Student, [5]byte, map[string]uint8")
	fmt.Println("reflect.Value 是对 value 的封装, 对 value 的操作, 通常使用 reflect.ValueOf() 获取")
	fmt.Println("reflect.Kind 表示变量所属的类别 例如 array, slice, map, struct, 通常使用 func (v Value) Kind() Kind 获取")
	fmt.Println(tab, "reflect.Kind 常量 ", "Invalid Bool Int Int8 Int16 Int32 Int64 Uint Uint8 Uint16 Uint32 Uint64 Uintptr Float32 Float64 Complex64 Complex128 Array Chan Func Interface Map Ptr Slice String Struct UnsafePointer")
	fmt.Println(tab, "当变量为基本数类型时, Type 和 Kind 有可能相同")
	fmt.Println(tab, "int 类型变量 Type 和 Kind 都为 int, 见 doc_test.go, 结构体 类型变量 Type 为 包名.Type, Kind 为 struct, 见 doc_test.go")
	fmt.Println(tab, "所有指针变量的种类都是 Ptr, 指针变量的名称为空, 不是 *A")
	fmt.Println("---------------")

	fmt.Println("Value零值, 表示不持有某个值, 零值的 IsValid 方法返回 false, Kind 方法返回 invalid, String 方法返回 <invalid Value>, 所有其它方法都会 panic, 绝大多数函数和方法永远都不返回 Value零值")
	fmt.Println(tab, "Value零值使用 ValueOf(nil) 获取")
	fmt.Println("Value零值和零值的 Value 的区别, 零值的 Value 表示有类型和类型默认值的Value, 使用 Zero 可以获取,")
	fmt.Println("---------------")

	fmt.Println("从实例到 Type")
	fmt.Println("  func TypeOf(i interface{}) Type // 获取 Type")
	fmt.Println("---------------")
	fmt.Println("从实例到 Value")
	fmt.Println("  func ValueOf(i interface{}) Value // 获取 Value")
	fmt.Println("---------------")
	fmt.Println("从 Type 到 Value")
	fmt.Println(" Type 中只有类型信息, 不能直接获取 Value, 可以使用方法创建新的 Value")
	fmt.Println("  func New(typ Type) Value // 返回一个持有类型 typ 的新的零值的指针的 Value, 即返回值的 Type 为 PtrTo(typ)")
	fmt.Println("  func Zero(typ Type) Value // 返回一个持有类型 typ 的零值的 Value, 返回值不能修改也不会寻址. Value 零值和零值的 Value 的区别")
	fmt.Println("  func NewAt(typ Type, p unsafe.Pointer) Value // 返回一个持有类型 typ, 地址为 p 的值的指针的 Value")
	fmt.Println("---------------")
	fmt.Println("从 Value 到 Type")
	fmt.Println("  func (v Value) Type() Type // 返回 V 持有的值的类型的 Type")
	fmt.Println("---------------")
	fmt.Println("从 Value 到实例")
	fmt.Println("  func (v Value) CanInterface() bool // 返回 v 能否调用 interface 方法并不导致 panic")
	fmt.Println("  func (v Value) Interface() (i interface{}) // 返回 v 持有的值, 使用接口类型断言或者类型查询(switch)转换为具体的类型")
	fmt.Println("  func (v Value) Bool() bool // 返回 v 持有的布尔值, 如果 v 的 Kind 不是 Bool 会 panic")
	fmt.Println("  func (v Value) Float() float64 // 返回 v 持有的浮点数(表示为 float64), 如果 v 的 Kind 不是 float32,float64 会 panic")
	fmt.Println("  func (v Value) Int() int64 // 返回 v 持有的有符号整数(表示为 int64), 如果 v 的 Kind 不是 int,int8,int16,int32,int64 会panic")
	fmt.Println("  func (v Value) Uint() uint64 // 返回 v 持有的无符号整数(表示为 uint64), 如果 v 的 Kind 不是 uint,uint8,uint16,uint32,uint64 会 panic")
	fmt.Println("  func (v Value) Complex() complex128 // 返回 v 持有的复数(表示为 complex128), 如果 v 的 Kind 不是 complex64,complex128 会 panic")
	fmt.Println("  func (v Value) String() string // 返回 v 持有的值得字符串表示")
	fmt.Println("  func (v Value) Bytes() []byte // 返回 v 持有的 []byte 类型值, 如果 v 持有的值的类型不是 []byte 会 panic")
	fmt.Println("  func (v Value) Pointer() uintptr // 返回 v 持有的值的指针, 如果 v 的 Kind 不是 Chan,Func,Map,Ptr,Slice,UnsafePointer 会 panic")
	fmt.Println("---------------")
	fmt.Println("从 Value 的指针到值")
	fmt.Println("  func (v Value) Elem() Value // 返回 v 持有的接口保管的值的 Value 封装, 或者 v 持有的指针指向的值的 Value 分装,")
	fmt.Println("    // 如果 v 的 Kind 不是 interface 或者 Ptr 会panic, 如果 v 持有的值为 nil, 则返回 Value零值")
	fmt.Println("  func Indirect(v Value) Value // 返回 v 持有的指针指向的值的 Value, 如果 v 持有 nil 指针, 会返回 Value零值, 如果不持有指针会返回 v")
	fmt.Println("---------------")
	fmt.Println("Type 指针和值的相互转换")
	fmt.Println("  指针类型 Type 到值类型 Type: t.Elem() Type // 返回内部元素的 Type, 如果 t 的 Kind 不是Array,Chan,Map,Ptr或Slice会panic")
	fmt.Println("  值类型 Type 到指针类型 Type: func PtrTo(t Type) Type // 返回类型 t 的指针的类型")
	fmt.Println("---------------")
	fmt.Println("value 值的可修改性")
	fmt.Println("  func (v Value) CanSet() bool // 返回 v 持有的值是否可被修改, 只有 v 持有的值可以被寻址同时又不是来自非导出字段时才可以被修改,")
	fmt.Println("    // 返回值为 false 时, 调用 Set 或者任何限定类型的设置函数(如 SetInt,SetBool)都会 panic")
	fmt.Println("  func (v Value) Set(x Value) // 将 v 持有的值修改为 x 的持有值, 如果 v.CanSet() 返回 false 则panic, x 的持有值必须能直接赋给 v 持有值的类型")
	fmt.Println("  func (v Value) CanConvert(t Type) bool // go 1.17, 返回 v 持有的值能否被转换为 t 类型, 可以返回 true")
	fmt.Println("  func (v Value) Convert(t Type) Value // 将 v 持有的值转换为类型为 t 的值并返回该值的 Value 封装, 如果 go 转换规则不支持会 panic")
	fmt.Println("  func (v Value) Index(i int) Value // 返回 v 持有值的第 i 个元素, 如果 v 的 Kind 不是 Array、Chan、Slice、String或者 i 出界则会 panic")
	fmt.Println("Value 值的判断")
	fmt.Println("  func (v Value) IsZero() bool // 返回 v 持有的值是否为其类型的零值, 如果 v 无效会 panic")
	fmt.Println("  func (v Value) IsNil() bool")
	fmt.Println("    // 返回 v 持有的值是否为 nil, v 持有的值的 Kind 必须是slice、map、chan、func、interface、Pointer之一, 否则会 panic")
	fmt.Println("    // 如果 v 是通过使用某个值为 nil 的接口调用 ValueOf 创建的则返回 true, 如果 v 是 Value 零值会 panic")
	fmt.Println("  func (v Value) IsValid() bool")
	fmt.Println("    // 返回 v 是否持有一个值, 如果 v 是 Value 零值返回 false, 此时 v 除了 IsValid, String, Kind之外方法都会导致 panic")
	fmt.Println("    // 绝大多数函数和方法都不会返回 Value 零值")
	fmt.Println("---------------")

	// fmt.Println("-----------------------------------")
}
