package main

import "fmt"

func readme() {
	fmt.Println("context 是 go 中用来进程通信的一种方式, 底层是借助 channel 和 sync.Mutex 实现的")
	fmt.Println("包 context 定义了 Context 类型, 它携带了跨 API 边界和进程之间的截止日期、取消信号和其他请求范围的值.")
	fmt.Println("context 的创建和调用关系是有层级关系的, 第一个创建 context 的 goroutine 被称为 root 节点, root 节点负责创建一个实现 Context 接口的具体对象,")
	fmt.Println(" 并将该对象作为参数传递至新创建的 goroutine 作为其上下文, 下游 goroutine 继续封装该对象并以此类推向下传递")
	fmt.Println("它们之间的函数调用链必须传播 Context, 可以选择将其替换为使用 WithCancel, WithDeadline, WithTimeout 或 WithValue 创建的派生 Context")
	fmt.Println("当一个 Context 被取消时, 从它派生的所有 Context 也会被取消")
	fmt.Println("------------------")

	fmt.Println("使用原则")
	fmt.Println(tab, "不应将上下文存储在结构体类型中, 而应显式地传入函数, 并且放在函数形参列表的第一个位置, 通常命名为 ctx")
	fmt.Println(tab, "不要传递 nil 的 Context, 在不确定时应使用 context.TODO()")
	fmt.Println(tab, "使用 Context 的 Value 相关方法时只应该用于传递和请求相关的元数据, 不应传递一些可选参数")
	fmt.Println(tab, "同一个 Context 可以传递到不同的 goroutine 中, 且在多个 goroutine 可以安全访问")
	fmt.Println("------------------")

	fmt.Println("WithCancel, WithDeadline, WithTimeout 函数采用 Context(父级) 并返回派生的 Context(子级) 和 CancelFunc, 调用 CancelFunc 会取消子级及其子级, 删除父级对子级的引用,")
	fmt.Println(" 并停止任何关联的计数器, 未能调用 CancelFunc 会泄露子级及其子级, 直到父级被取消或计时器触发")
	fmt.Println("WithCancelCause 函数返回一个 CancelCauseFunc, 它接受一个错误并将其记录为取消原因, 在已取消的上下文或其任何子上下文上调用 Cause 可检索原因,")
	fmt.Println(" 如果未指定原因, Cause(c) 返回与 c.Err() 相同的值")
	fmt.Println("------------------")

	fmt.Println("func Background() Context")
	fmt.Println(tab, "// 返回一个非零的空上下文, 它永远不会被取消, 没有值, 没有生存时间, 通常由主函数、初始化和测试使用作为传入请求的顶级上下文")
	fmt.Println("func TODO() Context")
	fmt.Println(tab, "// 返回一个非零的空上下文, 当不清楚要使用哪个 context 或当它还不可用时, 应该使用 context.TODO")
	fmt.Println("------------------")

	fmt.Println("func WithValue(parent Context, key, val any) Context")
	fmt.Println(tab, "// 返回父级上下文的副本, 其中与 key 关联的值为 val, 仅将上下文值用于传输进程和 API 的请求范围的数据, 而不用于将可选参数传递给函数")
	fmt.Println(tab, "// 提供的键必需是可比较的, 并且不应是字符串类型或任何其他内置类型, 以避免使用上下文的包之间发生冲突")
	fmt.Println("func WithCancel(parent Context) (ctx Context, cancel CancelFunc)")
	fmt.Println(tab, "// 返回带有新 Done 通道的父级副本, 当调用返回的 CancelFunc 或关闭父级上下文的 Done 通道时(以先发生为准), 返回的上下文的 Done 通道将会关闭")
	fmt.Println(tab, "// 取消此上下文会释放与其关联的资源, 因此在此上下文中运行的操作完成后, 代码应立即调用取消")
	fmt.Println("func WithCancelCause(parent Context) (ctx Context, cancel CancelCauseFunc) // 1.20 add")
	fmt.Println(tab, "// 行为与 WithCancel 类似, 但返回 CancelCauseFunc 而不是 CancelFunc, 使用非零错误调用 cancel 会在 ctx 中记录该错误")
	fmt.Println(tab, "// 然后可以使用 context.Cause(c) 检索它, 使用 nil 调用 cancel 将原因设置为 Canceled")
	fmt.Println("func WithDeadline(parent Context, d time.Time) (Context, CancelFunc)")
	fmt.Println(tab, "// 返回父级上下文的副本, 并将截止日期调整为不晚于 d, 如果父级的截止日期已经早于 d, 则此函数在语义上等同于 parent,")
	fmt.Println(tab, "// 当截止时间到期、调用返回的 CancelFunc 时或当父级上下文的 Done 通道关闭时(以先发生为准), 返回的上下文 Done 通道将会关闭")
	fmt.Println(tab, "// 取消此上下文会释放与其关联的资源, 因此在此上下文中运行的操作完成后, 代码应立即调用取消")
	fmt.Println("func WithDeadlineCause(parent Context, d time.Time, cause error) (Context, CancelFunc) // 1.21 add")
	fmt.Println(tab, "// 行为类似于 WithDeadline, 会在超时时设置上下文的原因, 返回的 CancelFunc 不会设置原因")
	fmt.Println("func WithTimeout(parent Context, timeout time.Duration) (Context, CancelFunc)")
	fmt.Println(tab, "// 行为与 WithDeadline 类似, 区别是接收的第二个参数为超时时间而不是截止时间")
	fmt.Println(tab, "// 取消此上下文会释放与其关联的资源, 因此在此上下文中运行的操作完成后, 代码应立即调用取消")
	fmt.Println("func WithTimeoutCause(parent Context, timeout time.Duration, cause error) (Context, CancelFunc) // 1.21 add")
	fmt.Println(tab, "// 行为类似于 WithTimeout, 会在超时时设置上下文的原因, 返回的 CancelFunc 不会设置原因")
	fmt.Println("------------------")

	fmt.Println("func Cause(c Context) error //  1.20 add")
	fmt.Println(tab, "// 返回一个非零错误, 解释 c 被取消的原因, c 或其父母之一的第一次取消决定了原因")
	fmt.Println(tab, "// 如果通过调用 CancelCauseFunc(err) 发生取消, 则 Cause 返回 err, 否则 Cause(c) 返回与 c.Err() 相同的值")
	fmt.Println(tab, "// 如果 c 尚未取消, Cause 返回 nil")
	fmt.Println("type CancelCauseFunc func(cause error)")
	fmt.Println(tab, "// 行为类似于 CancelFunc, 但还没设置取消原因, 可以通过在已取消的上下文或其任何派生上下文上调用 Cause 来检索")
	fmt.Println(tab, "// 如果上下文已被取消, CancelCauseFunc 不会设置原因, 如果 childContext(Cause2) 派生自 parentContext(Cause1)")
	fmt.Println(tab, "  // 如果在使用 Cause2 取消 childContext 之前使用 Cause1 取消 parentContext, 则 Cause(parentContext) == Cause(childContext) = Cause1")
	fmt.Println(tab, "  // 如果在使用 Cause1 取消 parentContext 之前使用 Cause2 取消 childContext, 则 Cause(parentContext) == Cause1 且 Cause(childContext) == Cause2")
	fmt.Println("type CancelFunc func()")
	fmt.Println(tab, "// 告诉操作放弃其工作, CancelFunc 不会等待工作停止, CancelFunc 可以被多个 goroutine 同时调用, 第一次调用后, 后续的调用不会执行任何操作")
	fmt.Println("------------------")

	fmt.Println("Context 接口的 4 个方法")
	fmt.Println(tab, "Deadline 方法返回此 Context 被取消的截止日期和标识, 如果没有设置 deadline, 则 ok == false, deadline 为一个零值 time.Time")
	fmt.Println(tab, "Done 方法返回一个只读 channel, 在 Context 被取消时, channel 会被 close, 使用 select-case 语句检测 Context 是否被取消, 如果 Context 永不取消, 则返回 nil")
	fmt.Println(tab, " 通知和 Context 相关的函数停止当前工作然后返回")
	fmt.Println(tab, "Err 方法返回 Context 被取消的原因, 如果尚未取消则返回 nil")
	fmt.Println(tab, " 因 deadline 关闭: context deadline exceeded")
	fmt.Println(tab, " 因 主动 关闭: context canceled")
	fmt.Println(tab, "Value 方法返回 Context 中和指定的 key 关联的 value, 该方法根据 key 值查询 map 中的 value")
	fmt.Println("------------------")
}
