package main

import (
	"bytes"
	"fmt"
	"strings"
)

func GCNote() {
	// https://mp.weixin.qq.com/s/a1gtHznuYeLVuNPVPYGCwg
	fmt.Println("--------GCNote()----------")
	fmt.Println("GC: 对不再使用的内存资源进行自动回收的功能称为垃圾回收, 是一种自动内存管理机制")
	fmt.Println(tab, "识别垃圾")
	fmt.Println(tab, tab, "引用计数算法(reference counting): 通过在对象上增加自己被引用的次数, 被其他对象引用时加1, 引用自己的对象被回收时减1, 引用数为0的对象即为可以被回收的对象")
	fmt.Println(tab, tab, tab, "优点")
	fmt.Println(tab, tab, tab, tab, "1. 方式简单, 回收速度快")
	fmt.Println(tab, tab, tab, "缺点")
	fmt.Println(tab, tab, tab, tab, "1. 需要额外的空间存放计数")
	fmt.Println(tab, tab, tab, tab, "2. 无法处理循环引用, 如 a.b = b, b.a = a")
	fmt.Println(tab, tab, tab, tab, "3. 频繁更新引用计数降低了性能")
	fmt.Println(tab, tab, "追踪式回收算法(Tracing):  判断一个对象是否可达, 如果这个对象一旦不可达就可以立刻被GC回收了")
	fmt.Println(tab, tab, tab, "第一步, 从根节点开始找出所有的全局变量和当前函数栈里的变量, 标记为可达. ")
	fmt.Println(tab, tab, tab, "第二步, 从已经标记的数据开始, 进一步标记它们可访问的变量, 依此类推, 专业术语叫\"传递闭包\", 当追踪结束时, 没有被打上标记的对象就被判定为不可触达")
	fmt.Println(tab, tab, tab, "优点")
	fmt.Println(tab, tab, tab, tab, "1. 解决了循环引用的问题")
	fmt.Println(tab, tab, tab, tab, "2. 占用的空间少了")
	fmt.Println(tab, tab, tab, "和引用计数相比, 缺点")
	fmt.Println(tab, tab, tab, tab, "1. 无法立刻识别出垃圾对象, 需要依赖 GC 线程")
	fmt.Println(tab, tab, tab, tab, "2. 算法在标记时必须暂停整个程序, 即 STW(stop the world), 否则其他线程有可能会修改对象的状态从而回收不该回收的对象")
	fmt.Println(tab, "清理垃圾")
	fmt.Println(tab, tab, "标记清除算法(Mark Sweep): 执行过程可以分成标记(Mark)和清除(Sweep)两个阶段")
	fmt.Println(tab, tab, tab, "标记阶段: 暂停应用程序的执行, 从根对象触发查找并标记堆中所有存活的对象")
	fmt.Println(tab, tab, tab, "清除阶段: 遍历堆中的全部对象, 回收未被标记的垃圾对象并将回收的内存加入空闲链表, 恢复应用程序的执行")
	fmt.Println(tab, tab, tab, "优点")
	fmt.Println(tab, tab, tab, tab, "1. 实现简单")
	fmt.Println(tab, tab, tab, tab, "2. 并发性, Go 的垃圾收集器与程序的执行同时进行, 最小化了暂停和中断, 对于需要低延迟和实时处理的应用程序至关重要")
	fmt.Println(tab, tab, tab, tab, "3. 自动管理, Go 的垃圾收集器自动运行, 解除了手动内存管理的负担, 促使了更加流畅的开发过程, 并降低了与内存相关的错误的发生几率")
	fmt.Println(tab, tab, tab, tab, "4. 内存安全性, Go 中的垃圾回收有助于防止内存泄漏")
	fmt.Println(tab, tab, tab, tab, "5. 性能优化")
	fmt.Println(tab, tab, tab, "缺点")
	fmt.Println(tab, tab, tab, tab, "1. 执行期间需要把整个程序完全停掉, 不能异步的进行垃圾回收")
	fmt.Println(tab, tab, tab, tab, "2. 容易产生大量不连续的内存碎片, 碎片太多可能会导致后续没有足够的连续内存分配给较大的对象, 从而提前触发新的一次垃圾回收动作")
	fmt.Println(tab, tab, "标记复制算法: 将内存空间划分为两个相等的区域, 每次只使用其中一个区域, 在垃圾回收时, 遍历当前使用的区域, 把存活对象复制到另一个区域中, 最后将当前使用的区域的可回收对象进行回收")
	fmt.Println(tab, tab, tab, "优点")
	fmt.Println(tab, tab, tab, tab, "1. 不用进行大量垃圾对象的扫描, 标记复制算法需要从 GC-root 对象出发, 将可达的对象复制到另外一块内存后直接清理当前这块内存即可")
	fmt.Println(tab, tab, tab, tab, "2. 解决了内存碎片问题, 防止分配大空间对象是提前 GC 的问题")
	fmt.Println(tab, tab, tab, "缺点")
	fmt.Println(tab, tab, tab, tab, "1. 复制成本问题, 在可达对象占用内存高的时候, 复制成本会很高")
	fmt.Println(tab, tab, tab, tab, "2. 内存利用率低, 相当于可利用的内存仅有一半")
	fmt.Println(tab, tab, "标记压缩算法: 在标记可回收的对象后将所有存活的对象压缩到内存的另一端, 使它们紧凑地排列在一起, 然后对边界以外的内存进行回收, 回收后, 已用和未用的内存都各自一边")
	fmt.Println(tab, tab, tab, "优点")
	fmt.Println(tab, tab, tab, tab, "1. 避免了内存碎片化的问题")
	fmt.Println(tab, tab, tab, tab, "2. 适合老年代算法, 老年代对象存活率高的情况下, 标记整理算法由于不需要复制对象, 效率高")
	fmt.Println(tab, tab, tab, "缺点")
	fmt.Println(tab, tab, tab, tab, "1. 整理过程复杂, 需要多次遍历内存, 导致 STW 时间比标记清除算法高")
	fmt.Println("------------------")

	fmt.Println("三色标记算法: Go 1.5 实现了基于三色标记清除的并发垃圾收集器, 属于增量式 GC 算法, 回收器首先将所有对象标记成白色, 然后从 gc root 出发, 逐步把所有可达的对象变成灰色再到黑色, 最终所有白色对象都是不可达对象")
	fmt.Println(tab, "白色对象: 潜在的垃圾, 表示还未搜索到的对象, 其内存可能会被垃圾收集器回收")
	fmt.Println(tab, "黑色对象: 活跃的对象, 表示搜索完成的对象, 包括不存在任何引用外部指针的对象以及从根对象可达的对象")
	fmt.Println(tab, "灰色对象: 活跃的对象, 表示正在搜索还未搜索完的对象, 因为存在指向白色对象的外部指针, 垃圾收集器会扫描这些对象的子对象")
	fmt.Println(tab, "步骤: ")
	fmt.Println(tab, tab, "1. 初始时所有对象都是白色的")
	fmt.Println(tab, tab, "2. 从 gc root 对象出发, 扫描所有可达对象标记为灰色, 放入待处理队列")
	fmt.Println(tab, tab, "3. 从队列取出一个灰色对象并标记为黑色, 将其引用对象标记为灰色, 放入队列")
	fmt.Println(tab, tab, "4. 重复上一步骤, 直到灰色对象队列为空")
	fmt.Println(tab, tab, "5. 此时剩下的所有的白色对象都是垃圾对象")
	fmt.Println(tab, "优点")
	fmt.Println(tab, tab, "1. 不需要 STW")
	fmt.Println(tab, "缺点")
	fmt.Println(tab, tab, "1. 如果产生垃圾速度大于回收速度时, 可能会导致程序中垃圾对象越来越多而无法及时收集")
	fmt.Println(tab, tab, "2. 线程切换和上下文转换的消耗会使得垃圾回收的总体成本上升, 从而降低系统吞吐量三色标记法存在并发性问题")
	fmt.Println(tab, tab, "3. 可能会出现野指针(指向没有合法地址的指针), 从而造成严重的程序错误")
	fmt.Println(tab, tab, "4. 漏标, 错误的回收非垃圾对象")
	fmt.Println(tab, "垃圾收集执行周期")
	fmt.Println(tab, tab, "清除终止、标记、标记中止、清除")
	fmt.Println("------------------")

	fmt.Println("GC调优: 减少堆内存的分配是最好的优化方式")
	fmt.Println(tab, "尽量避免 string 和 []byte 之间的转化, string 是基础只读类型, 对 string 的每一个操作都会创建一个新的 string")
	fmt.Println(tab, "少量小文本拼接使用 \"+\"")
	fmt.Println(tab, "大量小文本拼接使用 strings.Join")
	var strSlice = []string{"A", "b", "C", "d", "E", "f", "G", "h", "I", "j", "K", "l", "M", "n"}
	str := strings.Join(strSlice, "-")
	fmt.Print(tab, tab)
	fmt.Printf("strings.Join(a []string, sep string) string 值为 %v\n", str)
	fmt.Println(tab, "大量大文本拼接使用 bytes.Buffer")
	bf := bytes.NewBuffer([]byte("hello world"))
	b, _ := bf.ReadByte()
	r, _, _ := bf.ReadRune()
	s, _ := bf.ReadString(' ')
	fmt.Print(tab, tab)
	fmt.Printf("bytes.NewBuffer([]byte(\"hello world\")) ReadByte() 值为 %q ReadRune() 值为 %q ReadString(' ') 值为 %v\n", b, r, s)
	fmt.Println("------------------")
}
